---
driver:
  name: vagrant

driver_config:
  network:
    - ["forwarded_port", {guest: 8080, host: 9090, auto_correct: true}]
    - ["private_network", {ip: "33.33.33.10"}]
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: policyfile_zero
  data_bags_path: test/fixtures/data_bags
  encrypted_data_bag_secret_key_path: 'secrets/fakey-mcfakerton'

platforms:
  # - name: ubuntu-14.04
  #   run_list:
  #     - recipe[apt]
  - name: centos-6.7
    run_list:
      - recipe[yum]

suites:
  - name: pipeline
