---
driver:
  name: vagrant

driver_config:
  network:
    - ["forwarded_port", {guest: 8080, host: 9090, auto_correct: true}]
    - ["private_network", {ip: "33.33.33.10"}]
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: policyfile_zero
  data_bags_path: test/fixtures/data_bags
  require_chef_omnibus: true
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk

platforms:
  # - name: ubuntu-14.04
  #   run_list:
  #     - recipe[apt]
  - name: centos-6.6
    run_list:
      - recipe[yum]

suites:
  - name: pipeline
    # run_list:
    #   - recipe[pipeline_test]
    #   - recipe[emacs]
    #   - recipe[pipeline::jenkins]
    #   - recipe[pipeline::chefdk]
    #   - recipe[chef-zero]
    #   - recipe[pipeline::knife]
    #   - recipe[pipeline::jobs]
    # attributes:
    #   chef-zero:
    #     start: true
    #   pipeline:
    #     template:
    #       cookbook: pipeline_test
