---
driver:
  name: vagrant
  ssh:
    insert_key: false

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

  - name: centos-6.8
    run_list:
      - recipe[yum]

  - name: centos-7.2
    run_list:
      - recipe[yum]

suites:
  - name: pipeline
    run_list:
      - recipe[pipeline_test]
      - recipe[pipeline::jenkins]
      - recipe[pipeline::chefdk]
      - recipe[chef-zero]
      - recipe[pipeline::knife]
      - recipe[pipeline::jobs]
    attributes:
      chef-zero:
        start: true
      pipeline:
        template:
          cookbook: pipeline_test

  - name: provisioner
    run_list:
      - recipe[pipeline_test::hostsfile]
      - recipe[pipeline::jenkins]
      - recipe[pipeline::jenkins_auth]
      - recipe[pipeline::jenkins_cert_fix]
    driver:
      network:
        - ["private_network", {ip: "33.33.33.20"}]
      customize:
        memory: 2048
        cpus: 2
    attributes:
      pipeline:
        github:
          server: 'gitlab.mycompany.com'
